baseurl: ""
url: "https://humanuscrit.com"

title: Humanuscrit
theme: minima

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: "a-propos.md"
    values:
      permalink: /a-propos/

header_pages:
  - textes/index.md
  - productions/index.md
  - a-propos.md
